"""Core functionality for the Provium platform."""

from importlib.metadata import version

__version__ = version("provium")

from .artifact import (
    Artifact,
    ArtifactCatalog,
    ArtifactDefinition,
    ArtifactHeader,
    ArtifactReadBinding,
    ArtifactReader,
    ArtifactWriteBinding,
    ArtifactWriter,
    BodyRegion,
    StagedArtifact,
    decode_header,
    discover_artifact_catalogs,
    encode_header,
    read_artifact_header,
    reset_artifact_discovery,
    stage_artifact,
)
from .artifact.inspection import (
    FinalizedArtifactInspection,
    inspect_finalized_artifact,
)
from .cli import CLI_PLUGIN_API_VERSION, CLI_PLUGIN_ENTRY_POINT_GROUP, CLIPlugin
from .procedure import (
    CancellationToken,
    ConfigurationSnapshot,
    ImperativeProcedure,
    ImperativeProcedureExecution,
    JsonValue,
    PreparedProcedure,
    Procedure,
    ProcedureCancelledError,
    ProcedureCatalog,
    ProcedureConfig,
    ProcedureConfigurationError,
    ProcedureContract,
    ProcedureContractMetadata,
    ProcedureDefinition,
    ProcedureExecutionResult,
    ProcedureExecutionSession,
    ProcedureExecutor,
    ProcedureInputField,
    ProcedureInputs,
    ProcedureIOField,
    ProcedureIOFieldMetadata,
    ProcedureOptionalInputField,
    ProcedureOptionalOutputField,
    ProcedureOutputField,
    ProcedureOutputResult,
    ProcedureOutputs,
    ProcedureProcessContext,
    ProcedureRepeatedInputField,
    ProcedureSetupContext,
    compose_configuration,
    discover_procedure_catalogs,
    input,
    load_json_configuration,
    load_yaml_configuration,
    optional_input,
    optional_output,
    output,
    repeated_input,
    reset_procedure_discovery,
    validate_procedure_configuration,
)
from .provenance import (
    ArtifactLineage,
    ArtifactRecord,
    ArtifactReference,
    ProcedureExecutionRecord,
    ProcedureRecord,
)
from .session import Session, current_session, session
from .tool.visualization import lineage_to_dot, lineage_to_mermaid, render_lineage

# Compatibility version for Provium's public core integration contracts.
PROVIUM_CORE_API_VERSION = 1

__all__ = [
    "PROVIUM_CORE_API_VERSION",
    "CLI_PLUGIN_API_VERSION",
    "CLI_PLUGIN_ENTRY_POINT_GROUP",
    "CLIPlugin",
    "Artifact",
    "ArtifactCatalog",
    "ArtifactDefinition",
    "ArtifactHeader",
    "FinalizedArtifactInspection",
    "ArtifactLineage",
    "ArtifactReadBinding",
    "ArtifactReader",
    "ArtifactRecord",
    "ArtifactReference",
    "ArtifactWriter",
    "BodyRegion",
    "StagedArtifact",
    "ArtifactWriteBinding",
    "ConfigurationSnapshot",
    "ImperativeProcedure",
    "ImperativeProcedureExecution",
    "CancellationToken",
    "JsonValue",
    "PreparedProcedure",
    "Procedure",
    "ProcedureCatalog",
    "ProcedureCancelledError",
    "ProcedureConfig",
    "ProcedureConfigurationError",
    "ProcedureContract",
    "ProcedureContractMetadata",
    "ProcedureDefinition",
    "ProcedureExecutionRecord",
    "ProcedureExecutionSession",
    "ProcedureExecutionResult",
    "ProcedureOutputResult",
    "ProcedureExecutor",
    "ProcedureIOField",
    "ProcedureIOFieldMetadata",
    "ProcedureInputField",
    "ProcedureInputs",
    "ProcedureOptionalInputField",
    "ProcedureOptionalOutputField",
    "ProcedureOutputField",
    "ProcedureOutputs",
    "ProcedureProcessContext",
    "ProcedureRepeatedInputField",
    "ProcedureRecord",
    "ProcedureSetupContext",
    "Session",
    "__version__",
    "compose_configuration",
    "current_session",
    "decode_header",
    "discover_artifact_catalogs",
    "discover_procedure_catalogs",
    "encode_header",
    "input",
    "inspect_finalized_artifact",
    "lineage_to_dot",
    "lineage_to_mermaid",
    "load_json_configuration",
    "load_yaml_configuration",
    "optional_input",
    "optional_output",
    "output",
    "repeated_input",
    "render_lineage",
    "read_artifact_header",
    "reset_artifact_discovery",
    "reset_procedure_discovery",
    "session",
    "stage_artifact",
    "validate_procedure_configuration",
]
